# Generated by Django 3.2 on 2021-05-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='new_vektor',
            new_name='new_vector',
        ),
    ]
