# Generated by Django 3.2 on 2021-05-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_rename_new_vektor_operation_new_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('add', 'addition'), ('mult', 'multiplication')], max_length=100),
        ),
        migrations.AlterField(
            model_name='operation',
            name='vectors',
            field=models.ManyToManyField(to='node.Vector', verbose_name='Vector'),
        ),
    ]
